name = "SPSSTools"
uuid = "f3c7b0da-9b65-42be-a7e0-a12b8c4dbe74"
authors = ["PharmCat <v.s.arnautov@yandex.ru>"]
version = "0.1.0"

[deps]

Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]

Tables = "1"

[extras]

Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]

test = [ "Test"]
